### ISSUE TITLE
"Connect to TOR/Proxy" pop up terminal window doesn't work

### ISSUE THREAD

**Issue by x-originating-ip** [MBHudson/Vigilante-Toolset#3]
The terminal window that is supposed to appear in which to enter a URL doesn't seem to function as it should do on either OSs I've tried (both Ubuntu and Kali Linux). 

Opening option "1) Vigilance/Recon" followed by "1) Connect to TOR/Proxy" produces a terminal window which instantly opens and instantly closes again leaving the user unable to set a TOR target and therefore unable to utilise the tool :( 

Latest stable Ubuntu and Kali Linux versions utilised.

**Comment by MBHudson** [comment]
Did you run the installer? If you did, did you enter the correct $USER...?
Working fine with Kubuntu and Kali as of today (01/28/2022) 
If this doesn't help please post your line #20 from /home/$USER/Vigilante-Toolset/proxy.sh
-thanks!

**Comment by languidflame** [comment]
Thanks MB. Had the right username but turned out to be a weird misconfig error in the way my shells were setup. All sorted with a fresh Kali image - though now in my fresh image, when I enter a TOR address into the pop up prompt and tap enter nothing happens and my main menu shell won't accept any input. Is it hanging?
